production:
  tags:
    - shared
  only:
    - master@zhoujie/yiwise-official-BBS
  image: yiwise/alpine:deploy
  stage: deploy
  script:
    - ls -la
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_TEST" > ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # - echo $TEST_SERVER
    # - ifconfig
    # - cat ~/.ssh/id_dsa
    - rsync -rav ./ $TEST_SERVER
